version: '1'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql-test
    restart: always
    ports:
      - 3306:3306 # HOST:CONTAINER
    environment:
      MYSQL_ROOT_PASSWORD: testabst
      MYSQL_DATABASE: ticker
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: ticker
      MYSQL_PASSWORD: mega2011
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci